[[plugins]]
package = "netlify-plugin-nimbella"

[build]
  base = "."
  publish = "web/public"
  command = "cd web && npm install && npm run build"

[nimbella]
  path = "/api/"

[template.environment]
  NIMBELICIOUS_PASSWORD = "specify the password here"
