[[plugins]]
package = "netlify-plugin-nimbella"

[build]
  base = "."
  publish = "web/public"
  command = "cd web && npm install && npm run build"

[nimbella]
  path = "/api/v1/web"

[template.environment]
  NIMBELICIOUS_PASSWORD = "specify your password here"
  NIMBELLA_LOGIN_TOKEN = "get it from nimbella.com/signup"
