[[plugins]]
package = "netlify-plugin-nimbella"

[nimbella]
path = "/api/"

[build]
  base = "."
  publish = "web/public"
  command = "cd web && npm install && npm run build"

[template.environment]
  NIMBELICIOUS_PASSWORD = "specify the password here"
